// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"
)

type Transaction struct {
	TransactionID       int64     `json:"transaction_id"`
	UserID              int32     `json:"user_id"`
	TransactionCategory string    `json:"transaction_category"`
	TransactionAccount  string    `json:"transaction_account"`
	TransactionDate     time.Time `json:"transaction_date"`
	TransactionAmount   string    `json:"transaction_amount"`
	TransactionNotes    string    `json:"transaction_notes"`
	TransactionImageUrl string    `json:"transaction_image_url"`
	TransactionVerified bool      `json:"transaction_verified"`
}

type User struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
